import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mpadula
 */
public class usersWindow extends javax.swing.JFrame {

    /**
     * Creates new form usersWindow
     */
    public usersWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        departmentNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        coursNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        groupNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        subjectNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        markField = new javax.swing.JComboBox();
        generateButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        closeItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa studenta", "Nazwa wydziału", "Nazwa kierunku", "Nazwa grupy", "Nazwa przedmiotu", "Ocena końcowa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jButton1.setText("Usuń rekord");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setText("Nazwa studenta");
        jPanel1.add(jLabel1);
        jPanel1.add(studentNameField);

        jLabel2.setText("Nazwa wydziału");
        jPanel1.add(jLabel2);
        jPanel1.add(departmentNameField);

        jLabel3.setText("Nazwa kierunku");
        jPanel1.add(jLabel3);
        jPanel1.add(coursNameField);

        jLabel5.setText("Nazwa przedmiotu");
        jPanel1.add(jLabel5);
        jPanel1.add(groupNameField);

        jLabel4.setText("Nazwa grupy");
        jPanel1.add(jLabel4);
        jPanel1.add(subjectNameField);

        jLabel6.setText("Ocena końcowa");
        jPanel1.add(jLabel6);

        markField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2.0", "3.0", "3.5", "4.0", "4.5", "5.0" }));
        jPanel1.add(markField);

        generateButton.setText("Generuj");
        geozmiar

    }//GEN-LAST:event_addItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // DefaultTableModel model=(DefaultTableModel) studentTable.getModel();
        //int []rowToDelete=studentTable.getSelectedRows();

        
        DefaultTableModel model=(DefaultTableModel) studentTable.getModel();
   int[] rows = studentTable.getSelectedRows();
   for(int i=0;i<rows.length;i++){
     model.removeRow(rows[i]-i);
   }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
         String name="Jan Kowalski";
         String departmentName="WIMiIP";
         String courseName="Informatyka Stosowana";
         String groupName="M03";
         String subjectName="Programowanie w Java";
         Double mark=5.0;
        DefaultTableModel model=(DefaultTableModel) studentTable.getModel();
           Object[] row = { name,departmentName,courseName, groupName,subjectName,mark };
        model.addRow(row);    }//GEN-LAST:event_generateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void openWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usersWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usersWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usersWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usersWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usersWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addItem;
    private javax.swing.JMenuItem closeItem;
    private javax.swing.JTextField coursNameField;
    private javax.swing.JTextField departmentNameField;
    private javax.swing.JButton generateButton;
    private javax.swing.JTextField groupNameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox markField;
    private javax.swing.JTextField studentNameField;
    private javax.swing.JTable studentTable;
    private javax.swing.JTextField subjectNameField;
    // End of variables declaration//GEN-END:variables
}
